version: "3"

services:
  splashserver:
    container_name: splashserver
    image: scrapinghub/splash:latest
    restart: always
    ports:
      - 8050:8050
    networks:
      - splashservernetwork
    volumes:
      - ./splash/filters:/etc/splash/filters
      - ./splash/proxy-profiles:/etc/splash/proxy-profiles
      - ./splash/js-profiles:/etc/splash/js-profiles
      - ./splash/lua_modules:/etc/splash/lua_modules

networks:
  splashservernetwork:
#volumes:
  #splashfilters:
  #splashproxyprofiles:
  #splashjsprofiles:
  #splashluamodules: